---
title: "Lab_6"
author: "Christina Lin"
date: "10/1/2021"
output: 
  github_document:
  html_document:
    html_preview:false
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
if (!file.exists("mtsamples.csv"))
  download.file(
    url = "https://raw.githubusercontent.com/USCbiostats/data-science-data/master/00_mtsamples/mtsamples.csv",
    destfile = "mtsamples.csv",
    method   = "libcurl",
    timeout  = 60
    )
mtsamples <- read.csv("mtsamples.csv")

library(dplyr)
library(ggplot2)
library(tidyverse)
library(tidytext)
```



```{r}
mtsamples <- as_tibble(mtsamples)
```

# Question 1: What specialties do we have?
```{r}
specialties <- mtsamples %>%
  count(medical_specialty)

specialties %>%
  arrange(desc(n)) %>%
  top_n(15) %>%
  knitr::kable()

```

There are `r nrow(specialties)` specialties. Looking at the distribution:

```{r}
ggplot(mtsamples,aes(x = medical_specialty)) +
  geom_histogram(stat = "count") +
  coord_flip()
```

The specialties are not evenly distributed.



# Question 2: Most frequent words in transcription column

```{r, cache = TRUE}
mtsamples %>%
  unnest_tokens(output = token,input = transcription) %>%
  count(token) %>%
  top_n(20,n) %>%
  ggplot(aes(n, fct_reorder(token,n))) + 
  geom_col()
```

The word "patient" seems to be important, but we observe a lot of stop words. 


# Question 3: Removing the stop words

```{r}
mtsamples %>%
  unnest_tokens(output = token,input = transcription) %>%
  anti_join(stop_words, by = c("token" = "word")) %>%
  count(token) %>%
  top_n(20,n) %>%
  ggplot(aes(n, fct_reorder(token,n))) + 
  geom_col()
```


