---
title: "Lab 9"
author: "Christina Lin"
date: "11/5/2021"
output: 
  html_document:
    html_preview: false
  github_document: default
  word_document: default
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RSQLite)
library(DBI)

```


```{r}

# Initialize a temporary in memory database
con <- dbConnect(SQLite(), ":memory:")

# Download tables
actor <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/actor.csv")
rental <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/rental.csv")
customer <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/customer.csv")
payment <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/payment_p2007_01.csv")

# Copy data.frames to database
dbWriteTable(con, "actor", actor)
dbWriteTable(con, "rental", rental)
dbWriteTable(con, "customer", customer)
dbWriteTable(con, "payment", payment)

# Are there tables there?
dbListTables(con)
```

This is equivalent to using 'dbGetQuery'.

```{r}
dbGetQuery(con, "PRAGMA table_info(actor)")
```


## Question 1:

```{r}
dbGetQuery(con, "
SELECT actor_id, first_name, last_name
FROM actor /* adding comments inline */
ORDER by last_name, first_name
LIMIT 5
")

# the LIMIT is same as head() in R to only display first 5 
```


## Question 2:

```{r}
dbGetQuery(con, "
SELECT actor_id, first_name, last_name
FROM actor
WHERE last_name IN ('WILLIAMS', 'DAVIS')
")

```
## Question 3:

```{r}
dbGetQuery(con, "
SELECT DISTINCT customer_id
FROM rental
WHERE date(rental_date) = '2005-07-05'
")

```
## Question 4:

Part 4.1
```{r}
q <- dbSendQuery(con, "
SELECT *
FROM payment
WHERE amount IN (1.99, 7.99, 9.99)
")

# Fetching the results 10 at a time 
dbFetch(q, n=10)
dbFetch(q, n=10)
dbClearResult(q) #this removes the results from memory
```


Part 4.2
```{r}
dbGetQuery(con, "
SELECT *
FROM payment
WHERE amount > 5
LIMIT 5
")
```
Part 4.3
```{r}
dbGetQuery(con, "
SELECT *
FROM payment
WHERE amount > 5 AND amount < 8
LIMIT 5
")
```

## Question 5:

```{r}
dbGetQuery(con, "
SELECT payment_id, amount
FROM payment
  INNER JOIN customer
WHERE customer.last_name = 'DAVIS'
AND payment.customer_id = customer.customer_id
")
```

# Question 6:

Part 6.1
```{r}
dbGetQuery(con, "
SELECT COUNT (*) AS nrows
FROM rental
")
```


Part 6.2
```{r}
dbGetQuery(con, "
SELECT customer_id, COUNT (*) AS count
FROM rental
GROUP BY customer_id
LIMIT 5
")
```

Part 6.3

```{r}
dbGetQuery(con, "
SELECT customer_id, COUNT (*) AS 'N Rentals'
FROM rental
GROUP BY customer_id
ORDER BY `N Rentals` DESC
LIMIT 5
")

```
Part 6.4

```{r}
dbGetQuery(con, "
SELECT customer_id, COUNT (*) AS count
FROM rental
GROUP BY customer_id
HAVING count >= 40
ORDER BY count DESC
")


```

## Question 7

```{r}
dbGetQuery(con, "
SELECT 
  AVG(amount) AS average,
  MAX(amount) AS maximum,
  MIN(amount) AS minimum,
  SUM(amount) AS sum
FROM payment
")

```

Part 7.1

```{r}
dbGetQuery(con, "
SELECT customer_id,
  AVG(amount) AS average,
  MAX(amount) AS maximum,
  MIN(amount) AS minimum,
  SUM(amount) AS sum
FROM payment
GROUP BY customer_id
LIMIT 5
")

```

Part 7.2

```{r}
dbGetQuery(con, "
SELECT customer_id,
  COUNT(*) AS N,
  AVG(amount) AS average,
  MAX(amount) AS maximum,
  MIN(amount) AS minimum,
  SUM(amount) AS sum
FROM payment
GROUP BY customer_id
HAVING COUNT(*) > 5
")
```


```{r}
dbDisconnect(con)
```

